name: Build & push container image, then deploy container on server

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-24.04
    env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: $DOCKERHUB_USERNAME/ci-cd-docker-go:${{ github.sha }}
