name: Build & push container image, then deploy container on server

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-docker-go:${{ github.sha }}

  deploy-to-server:
    runs-on: ubuntu-24.04
    needs: build-push-image
    steps:
      - name: Checkout to get docker compose & env file
        uses: actions/checkout@v4
      - name: Copy docker compose & env file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          source: './docker-compose.yaml,./.env'
          target: /app
      - name: SSH to server to deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /app
            sed -i 's/^GO_IMAGE_TAG=.*/GO_IMAGE_TAG=${{ github.sha }}/' .env
            docker compose --env-file .env up -d
